### ISSUE TITLE
Would be great if it could render published Google docs

### ISSUE THREAD

**Issue by jvprosser** [mattpalermo/asciidoctor-browser-renderer#2]
We use Google Docs to collaborate on Asciidoc content.
Currently we have to save it to disk in order to render it.
It would be great if we could publish the doc from with google docs and then have the URL content be rendered.

**Comment by mattpalermo** [comment]
Do you have an example URL that you could share? You might also want to suggest this to https://github.com/asciidoctor/asciidoctor-browser-extension to see if they can help as well.

**Comment by jvprosser** [comment]
Hi Matt,
We like to use google drive for collaboration.  It's a multistep process to
preview Asciidoc though.
https://docs.google.com/document/d/e/2PACX-1vRKJ2cFtXc3VxEESlxsmVWNs4I_324Dgq8ZvSFyjBxyqJONXfOiY3TG_4Nh1_lZpwNQ21FGJKcYRSrD/pub

I'll ask the asciidoctor browser extension folks as well.

**Comment by mattpalermo** [comment]
Hi jvprosser,

Given that Google docs doesn't do plain text, it's not ideal for asciidoc documents. So it's not something that I want to pursue. But if it's important to you, give a try at forking this and implementing it. I suggest trying to get some sort of plain text version of your document through `adoc = document.getElementById('contents').textContent`

Regards,
Matt
